name: Push to NPMJS
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  version-or-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Set version from tag
        run: |
          VERSION="${GITHUB_REF##*/}"
          VERSION="${VERSION#v}"
          echo "📦 Version from tag: $VERSION"
          npm version "$VERSION" --no-git-tag-version

      - name: Commit updated version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: release v${GITHUB_REF##*/}"
          git push origin HEAD:main


      - name: Build package
        run: npm run build

      - name: Create release PR or publish
        uses: changesets/action@v1
        with:
          publish: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
